#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-palmerpenguins
Version  : 0.1.1
Release  : 17
URL      : https://cran.r-project.org/src/contrib/palmerpenguins_0.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/palmerpenguins_0.1.1.tar.gz
Summary  : Palmer Archipelago (Antarctica) Penguin Data
Group    : Development/Tools
License  : CC0-1.0
BuildRequires : buildreq-R

%description
# palmerpenguins <a href='https://allisonhorst.github.io/palmerpenguins/'><img src='man/figures/logo.png' align="right" height="138.5" /></a>

%prep
%setup -q -n palmerpenguins
cd %{_builddir}/palmerpenguins

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1660582741

%install
export SOURCE_DATE_EPOCH=1660582741
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/palmerpenguins/CITATION
/usr/lib64/R/library/palmerpenguins/DESCRIPTION
/usr/lib64/R/library/palmerpenguins/INDEX
/usr/lib64/R/library/palmerpenguins/Meta/Rd.rds
/usr/lib64/R/library/palmerpenguins/Meta/data.rds
/usr/lib64/R/library/palmerpenguins/Meta/features.rds
/usr/lib64/R/library/palmerpenguins/Meta/hsearch.rds
/usr/lib64/R/library/palmerpenguins/Meta/links.rds
/usr/lib64/R/library/palmerpenguins/Meta/nsInfo.rds
/usr/lib64/R/library/palmerpenguins/Meta/package.rds
/usr/lib64/R/library/palmerpenguins/NAMESPACE
/usr/lib64/R/library/palmerpenguins/R/palmerpenguins
/usr/lib64/R/library/palmerpenguins/R/palmerpenguins.rdb
/usr/lib64/R/library/palmerpenguins/R/palmerpenguins.rdx
/usr/lib64/R/library/palmerpenguins/R/sysdata.rdb
/usr/lib64/R/library/palmerpenguins/R/sysdata.rdx
/usr/lib64/R/library/palmerpenguins/data/Rdata.rdb
/usr/lib64/R/library/palmerpenguins/data/Rdata.rds
/usr/lib64/R/library/palmerpenguins/data/Rdata.rdx
/usr/lib64/R/library/palmerpenguins/extdata/penguins.csv
/usr/lib64/R/library/palmerpenguins/extdata/penguins_raw.csv
/usr/lib64/R/library/palmerpenguins/help/AnIndex
/usr/lib64/R/library/palmerpenguins/help/aliases.rds
/usr/lib64/R/library/palmerpenguins/help/figures/README-flipper-bill-1.png
/usr/lib64/R/library/palmerpenguins/help/figures/README-flipper-hist-1.png
/usr/lib64/R/library/palmerpenguins/help/figures/README-mass-flipper-1.png
/usr/lib64/R/library/palmerpenguins/help/figures/culmen_depth.png
/usr/lib64/R/library/palmerpenguins/help/figures/logo.png
/usr/lib64/R/library/palmerpenguins/help/figures/lter_penguins.png
/usr/lib64/R/library/palmerpenguins/help/figures/palmerpenguins.png
/usr/lib64/R/library/palmerpenguins/help/palmerpenguins.rdb
/usr/lib64/R/library/palmerpenguins/help/palmerpenguins.rdx
/usr/lib64/R/library/palmerpenguins/help/paths.rds
/usr/lib64/R/library/palmerpenguins/html/00Index.html
/usr/lib64/R/library/palmerpenguins/html/R.css
